### ISSUE TITLE
Don't rewrite classes that have no tests

### ISSUE THREAD

**Issue by smoyer64** [boyarsky/convert-junit4-to-junit5#8]
The tool currently reformats all Java classes as they're analyzed by ``javaparser`` - this creates a lot of chatter in diff tools.

**Comment by boyarsky** [comment]
Good point. I like a variant of that idea - "don't rewrite classes that have no changes". (A helper class full of assertion calls should still change.) In fact, this was my original idea and there was an if statement int eh code to that effect. But when I added the javaparser call, it became dead code. So I added another guard that actually does this. 

Thanks for the suggestion.
